spring.application.name=hackaton_usuario

spring.datasource.url=jdbc:postgresql://localhost:5435/usuario_db
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Drive

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.format-sql=true
spring.datasource.initialization-mode=always